twig:
    paths:
        '%kernel.project_dir%/src/UI/Http/Web/Templates':  ~
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
