<?php

namespace ContainerCSAj5lq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineOrmFizzBuzzRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Persistence\Doctrine\FizzBuzz\DoctrineOrmFizzBuzzRepository' shared autowired service.
     *
     * @return \App\Infrastructure\Persistence\Doctrine\FizzBuzz\DoctrineOrmFizzBuzzRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/FizzBuzz/FizzBuzzRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/Doctrine/FizzBuzz/DoctrineOrmFizzBuzzRepository.php';

        return $container->privates['App\\Infrastructure\\Persistence\\Doctrine\\FizzBuzz\\DoctrineOrmFizzBuzzRepository'] = new \App\Infrastructure\Persistence\Doctrine\FizzBuzz\DoctrineOrmFizzBuzzRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
