<?php

namespace ContainerCSAj5lq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateFizzBuzzSequenceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Application\FizzBuzz\GenerateFizzBuzzSequence' shared autowired service.
     *
     * @return \App\Application\FizzBuzz\GenerateFizzBuzzSequence
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/FizzBuzz/GenerateFizzBuzzSequence.php';

        return $container->privates['App\\Application\\FizzBuzz\\GenerateFizzBuzzSequence'] = new \App\Application\FizzBuzz\GenerateFizzBuzzSequence(($container->privates['App\\Infrastructure\\Bus\\Messenger\\MessengerBusSymfony'] ?? $container->load('getMessengerBusSymfonyService')), ($container->privates['App\\Infrastructure\\Persistence\\Doctrine\\FizzBuzz\\DoctrineOrmFizzBuzzRepository'] ?? $container->load('getDoctrineOrmFizzBuzzRepositoryService')));
    }
}
