<?php

namespace ContainerCSAj5lq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateLogWhenFizzBuzzWasCreatedService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Domain\FizzBuzz\Listener\GenerateLogWhenFizzBuzzWasCreated' shared autowired service.
     *
     * @return \App\Domain\FizzBuzz\Listener\GenerateLogWhenFizzBuzzWasCreated
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/FizzBuzz/Listener/GenerateLogWhenFizzBuzzWasCreated.php';

        return $container->privates['App\\Domain\\FizzBuzz\\Listener\\GenerateLogWhenFizzBuzzWasCreated'] = new \App\Domain\FizzBuzz\Listener\GenerateLogWhenFizzBuzzWasCreated(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
