<?php

namespace ContainerCSAj5lq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessengerBusSymfonyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Bus\Messenger\MessengerBusSymfony' shared autowired service.
     *
     * @return \App\Infrastructure\Bus\Messenger\MessengerBusSymfony
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/Shared/Messenger/MessengerBusInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Bus/Messenger/MessengerBusSymfony.php';

        return $container->privates['App\\Infrastructure\\Bus\\Messenger\\MessengerBusSymfony'] = new \App\Infrastructure\Bus\Messenger\MessengerBusSymfony(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)));
    }
}
