<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLFrlSHc\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLFrlSHc/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLFrlSHc.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLFrlSHc\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLFrlSHc\App_KernelProdContainer([
    'container.build_hash' => 'LFrlSHc',
    'container.build_id' => '9ca71ae4',
    'container.build_time' => 1712823817,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLFrlSHc');
