<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'fizzbuzz' => [[], ['_controller' => 'App\\UI\\Http\\Web\\Controllers\\FizzBuzzController'], [], [['text', '/desafio/fizz/buzz']], [], [], []],
    'App\UI\Http\Web\Controllers\FizzBuzzController::__invoke' => [[], ['_controller' => 'App\\UI\\Http\\Web\\Controllers\\FizzBuzzController'], [], [['text', '/desafio/fizz/buzz']], [], [], []],
    'App\UI\Http\Web\Controllers\FizzBuzzController' => [[], ['_controller' => 'App\\UI\\Http\\Web\\Controllers\\FizzBuzzController'], [], [['text', '/desafio/fizz/buzz']], [], [], []],
];
