<?php

namespace ContainerPjD6QFM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBeginLessThanLastValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\UI\Http\Web\Forms\BeginLessThanLastValidator' shared autowired service.
     *
     * @return \App\UI\Http\Web\Forms\BeginLessThanLastValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/UI/Http/Web/Forms/BeginLessThanLastValidator.php';

        return $container->privates['App\\UI\\Http\\Web\\Forms\\BeginLessThanLastValidator'] = new \App\UI\Http\Web\Forms\BeginLessThanLastValidator();
    }
}
