<?php

namespace ContainerPjD6QFM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFizzBuzzControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\UI\Http\Web\Controllers\FizzBuzzController' shared autowired service.
     *
     * @return \App\UI\Http\Web\Controllers\FizzBuzzController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/UI/Http/Web/Controllers/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/UI/Http/Web/Controllers/FizzBuzzController.php';
        include_once \dirname(__DIR__, 4).'/src/Application/FizzBuzz/GenerateFizzBuzzSequence.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Shared/Messenger/MessengerBusInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Bus/Messenger/MessengerBusSymfony.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/FizzBuzz/FizzBuzzRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/Doctrine/FizzBuzz/DoctrineOrmFizzBuzzRepository.php';

        $container->services['App\\UI\\Http\\Web\\Controllers\\FizzBuzzController'] = $instance = new \App\UI\Http\Web\Controllers\FizzBuzzController(new \App\Application\FizzBuzz\GenerateFizzBuzzSequence(new \App\Infrastructure\Bus\Messenger\MessengerBusSymfony(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container))), new \App\Infrastructure\Persistence\Doctrine\FizzBuzz\DoctrineOrmFizzBuzzRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)))));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'security.token_storage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'twig' => ['privates', 'twig', 'getTwigService', false],
            'web_link.http_header_serializer' => ['privates', 'web_link.http_header_serializer', 'getWebLink_HttpHeaderSerializerService', false],
        ], [
            'form.factory' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'serializer' => '?',
            'twig' => '?',
            'web_link.http_header_serializer' => '?',
        ]))->withContext('App\\UI\\Http\\Web\\Controllers\\FizzBuzzController', $container));

        return $instance;
    }
}
