<?php

namespace ContainerLFrlSHc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_DYw0nSeService extends App_KernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.dYw0nSe' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.dYw0nSe'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Domain\FizzBuzz\Listener\GenerateLogWhenFizzBuzzWasCreated(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))), []);
    }
}
