<?php

namespace ContainerLFrlSHc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFizzBuzzControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\UI\Http\Web\Controllers\FizzBuzzController' shared autowired service.
     *
     * @return \App\UI\Http\Web\Controllers\FizzBuzzController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\UI\\Http\\Web\\Controllers\\FizzBuzzController'] = $instance = new \App\UI\Http\Web\Controllers\FizzBuzzController(new \App\Application\FizzBuzz\GenerateFizzBuzzSequence(new \App\Infrastructure\Bus\Messenger\MessengerBusSymfony(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'))), new \App\Infrastructure\Persistence\Doctrine\FizzBuzz\DoctrineOrmFizzBuzzRepository(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)))));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'security.token_storage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
            'web_link.http_header_serializer' => ['privates', 'web_link.http_header_serializer', 'getWebLink_HttpHeaderSerializerService', false],
        ], [
            'form.factory' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'serializer' => '?',
            'twig' => '?',
            'web_link.http_header_serializer' => '?',
        ]))->withContext('App\\UI\\Http\\Web\\Controllers\\FizzBuzzController', $container));

        return $instance;
    }
}
