<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCSAj5lq\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCSAj5lq/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCSAj5lq.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCSAj5lq\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerCSAj5lq\App_KernelTestDebugContainer([
    'container.build_hash' => 'CSAj5lq',
    'container.build_id' => 'fcd45c0e',
    'container.build_time' => 1712756619,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCSAj5lq');
